### ISSUE TITLE
Error: ensure config/app_config.yml has been edited and the settings are correct.

### ISSUE THREAD

**Issue by c08d555e** [cleesmith/rorshack#1]
Hi @cleesmith!!

I'm fairly certain I'm following your README instructions.  However, after editing this file and trying to run rorshack, I'm getting the following : 

"Error: ensure config/app_config.yml has been edited and the settings are correct."

If the issue really is with this file, can you provide an example of a working one?  I've only modified the "Change_Me" lines.

Thanks!

**Comment by cleesmith** [comment]
I hope you can get rorshack to work, but the message you are seeing only occurs when it can't find the 
file or find the ```environment``` setting in the file.  If you are running it on your own machine and not a 
production server then try changing ```production:``` to ```development:``` ... i.e. the top line of ```config/app_config.yml```.
Sorry about the confusion, it's just that in my day job all the instructions I write for installing software assume it's being done on a production server.
Let me know if that works, or anything else you notice.

**Comment by cleesmith** [comment]
Just in case you are actually installing/using a production server then you would need to to this:
```
sudo nano /etc/environment
... add these lines if not present:
    RAILS_ENV=production
    RACK_ENV=production
```
verify:
```
echo $RAILS_ENV
echo $RACK_ENV
```

**Comment by cleesmith** [comment]
You can also verify the rails environment by doing:
```
bundle exec rails console
Rails.env
 => "development" 
```

**Comment by cleesmith** [comment]
Also, I updated the instructions about settings for dev/prod and email

**Comment by c08d555e** [comment]
Hey Chris!

Thanks so much for your help.  I'm trying to set up rorshack on an AWS
instance that will be used in a live setting.  However, I'm not familiar
with what the differences are between production and dev from the
perspective of Rails.  That being said, I changed the first line in
config/app_config.yml to development and made it further before I got a new
error.  I think it just has to do with my ruby installation or something
though so I'll have to troubleshoot tonight when I get off of work.  :

line=dynamic or restricted.  An attacker can use this information to gain
insite

/var/lib/gems/1.9.1/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:443:in
`load': /home/home/rorshack/app/models/elastic_tool.rb:38: syntax error,
unexpected tLABEL, expecting ')' (SyntaxError)

  def nodes_jvm(node_id: '_local')

                        ^

/home/home/rorshack/app/models/elastic_tool.rb:38: syntax error, unexpected
')', expecting keyword_end

/home/home/rorshack/app/models/elastic_tool.rb:53: syntax error, unexpected
tLABEL, expecting ')'

  def nodes_process(node_id: '_local')

                            ^



Thanks for your responses!  I really do appreciate it.

Curtis

**Comment by cleesmith** [comment]
I have very little experience with AWS, but you definitely want to be in ```production``` mode not 
```development```.   Development is for use on your laptop or PC and is a lot slower than production 
because everything is reloaded on each request ... in other words, development mode is for coding/testing and not normal usage.  Not sure what those messages about ElasticTool are, but it 
doesn't look like you've installed ruby/gems correctly.  Did you try using RVM ?  A ```.ruby-version``` 
and ```.ruby-gemset``` are included for use with rvm.

**Comment by cleesmith** [comment]
I updated the installation instructions for non-sysadmins that aren't used to installing ruby on rails applications ... proper rvm and ruby setup.
Also, be sure you have Uni2EsPy up and running properly before installing Rorshack.

**Comment by c08d555e** [comment]
Awesome!  Thanks so much!  I'm excited to use it and I've already got
Uni2EsPy running on my clients and if I use the remote ES server, I can see
events in Kibana, so rorshack should be the last step.  One question I do
have though is that these IDS client sensors will be open to customers at
these sites and I'm hoping to protect ES from accidentally being wiped or
something.  I also want to make it scalable.  Is there a way to have
Uni2EsPy log to redis or logstash instead of directly to ES and if not, do
you know of a way of protecting ES?

Thanks again!
Curtis

**Comment by cleesmith** [comment]
I'm not sure I understand your setup, as I used to running sensors plus uni2espy/rorshack-like software on separate servers ... i.e. their own little island.
The only way to protect ES is to bind/listen on localhost:9200 behind all of the usual network protections (firewall, etc).  The folks at ES recently offered Shield to secure an ES install, but it's not open source or free.

**Comment by c08d555e** [comment]
Thanks again, I appreciate all of the information.  I'm really wanting to
get this working without bothering you, but I'm running into the same issue
now even after installing RVM properly this time.  Your steps really
helped, as there were several things I had not done properly previously.

This is the error I keep getting, even though I've edited the config.  Any
idea why this might be happening?  Do you have a config you could send me?
:

~/rorshack$ bundle exec rails runner lib/create_admin.rb

config/initializers/load_app_config.rb script was started via file 'rails'
with no args

**********************************************************************************************************************************

verifying app installation is correct . . .

Error: ensure config/app_config.yml has been edited and the settings are
correct.

**Comment by cleesmith** [comment]
At this point, you may want to contact/hire a sysadmin that's experienced at installing ruby/rails apps as 
you mentioned "customers" which sounds like a commercial venture ... and that's fine, but it's a bit 
much to ask from an open source project.  I know the app installs and works properly as I followed the 
instructions on a server here at home.

**Comment by c08d555e** [comment]
I understand and I want to say thanks again for the time you've spent to
help with this already.  I'm confident I can figure it out, just wanted to
make sure that error wasn't specific to rorshack but since you got it
working it must be something I'm doing then.  I was a Windows sysadmin
before but I've never dabbled in ruby/rails before so this project is a
little over my head.  It's just a home project right now but if I like it
I'm considering proposing this over Kibana for the Security Operations
Center I work in.

Great work and thanks again!
Curtis

**Comment by cleesmith** [comment]
We use an app like Rorshack, but with a lot more features, everyday, and some of the analysts use 
kibana as well ... i.e. they should compliment each other.  I "relaxed" some of the production double 
checks that were in the code ... just make sure your versions of ES and Java match what's in 
```
config/app_config.yml
... mine are:
jvm: 1.7.0_65
es_version: 1.2.2
```
... the double checking was done to ensure sysadmins were installing the app as expected thereby 
avoiding strange errors.
To be honest, if you "cut/paste" from the instructions going top to bottom the app really should install 
and run.
Thanks and good luck.

**Comment by c08d555e** [comment]
You got it!  I was just a dummy and had the java version wrong.  It's
working now!  Last question and I'll leave you alone forever. :)  What's
the default credentials for the :3000 interface?

Thanks a million!
Curtis

**Comment by cleesmith** [comment]
I'm not sure I understand the question, but do mean the login ?
If yes, when you did this:
```
bundle exec rails runner lib/create_admin.rb
```
... it created the default user:  ```admin``` with the password: ```changeme``` ... so login with those
... but the next time you install the app you can edit and change the password in ```lib/create_admin.rb```.

Questions are fine, just open a new issue, well, once you get past the install phase.
It would be nice if you ```gave back``` by offering enhancement suggestions, bug fixes, or other ideas.

**Comment by c08d555e** [comment]
I sure will provide that, thanks.

**Comment by c08d555e** [comment]
Chris,

I apologize, but I have one more question and did not want to post it in
the "issues" section in case it's just something I'm doing wrong.  Uni2ESpy
is working perfectly.  I'm getting events in Kibana named "snort" and I see
a lot of sensor data, as well as all rule data.

However, in rorshack everything is blank and I see no data at all.  The
host in my app_config.yml seems to be configured correctly.  Any idea why
this might be?  Thanks, and I feel bad to keep asking for your help but
there is no other information out there on this since you developed it. :)

Thanks,
Curtis

**Comment by c08d555e** [comment]
Please disregard!  I figured this out, my host was wrong in uni2espy.

Thanks,
Curtis

**Comment by cleesmith** [comment]
I know, it's a lot to configure and get right, but once you get the hang of it ... it just works.
The next challenge is getting a sentinel to email you an alert.  Tip: I always create a search/query 
that matches everything ... just to test that email works properly.

**Comment by c08d555e** [comment]
Awesome, I REALLY REALLY like this tool you've developed.  It's better than
I originally even anticipated!  I like the automatic whois.  I may have
some feature suggestions in the future and would even be willing to help
spend some time developing these myself to contribute back if interested.
Obviously I'm no developer outside of PHP, but I usually learn quickly and
can modify existing code pretty well.  Anyways, just wanted to say thanks
again.. this is exactly what I was looking for in an ES NSM portal. :)

**Comment by cleesmith** [comment]
Don't mean to sound uppity or rude, but Ruby is very different than PHP and takes a much longer time to learn well ... it's a purest thing I guess.  I'm also working on a python+flask version of rorshack, which 
should be far easier to install and hack on the code for non-rubyists.

To be honest, I'm mostly driven by the more robust app that my company uses 24/7 ... there are a ton more features, some of which will never be open sourced.

As this app is open source, feature suggestions are welcomed especially if you/someone finds them useful.
